#!/usr/bin/env bash
# This script installs and configures firewall to allow the following connections:
# SSH(22)
# HTTP(80)
# HTTPs(443)

apt-get update -y
apt-get install ufw -y

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp

ufw enable
